### ISSUE TITLE
Twilio Client for Android - Xamarin binding?

### ISSUE THREAD

**Issue by vsr-jsinh** [dkornev/TwilioXamarinBindings#9]
Hello,

Is this implementing "Twilio client for Android or iOS" like described here:
https://www.twilio.com/blog/2014/11/twilio-client-for-xamarin-part-3-android.html

appreciate your inputs in advance, thanks
-Jaspal

**Comment by dkornev** [comment]
Hi,

Not really. That article is about _twilio client sdk_, Twilio stopped the support for that about one year ago and replaced with the new generation _twili voice sdk_ https://www.twilio.com/docs/voice/voip-sdk/get-started

**Comment by vsr-jsinh** [comment]
@dkornev - Thanks for quick response - so to get a bit more info - this android Xamarin binding does the new `twilio voice sdk`? sorry i am new - needs some pointers

**Comment by dkornev** [comment]
I've just updated the twilio voice SDK binding for Android to v4.0.0 and moved it into a separate repository: https://github.com/dkornev/TwilioVoiceXamarinAndroid.

At first, you will need to check twilio's official quickstart application for Android (https://github.com/twilio/voice-quickstart-android) and start from that. I believe that it won't be hard to port it to C# because of C# and Java are very similar.

**Comment by vsr-jsinh** [comment]
@dkornev - Thanks. I will check and try to cook something up using this.
